export const REGISTER_PENDING = "REGISTER_PENDING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_ERRORS = "GET_ERRORS";

export const GET_DAILY_DATA = "GET_DAILY_DATA";
export const GET_DAILY_SUCCESS = "GET_DAILY_SUCCESS";
export const GET_DAILY_FAILURE = "GET_DAILY_FAILURE";

export const GET_WEEKLY_DATA = "GET_WEEKLY_DATA";

export const GET_MONTHLY_DATA = "GET_MONTHLY_DATA";

export const GET_YEARLY_DATA = "GET_YEARLY_DATA";

export const GET_YEARLY_ALL = "GET_YEARLY_ALL";

export const UPDATE_SLEEP_OBJECT = "UPDATE_SLEEP_OBJECT";

export const DELETE_SLEEP_OBJECT = "DELETE_SLEEP_OBJECT";

export const POST_SLEEP_OBJECT = "POST_SLEEP_OBJECT";
